Updated docksal config

diff --git a/.docksal/commands/refresh b/.docksal/commands/refresh
--- a/.docksal/commands/refresh
+++ b/.docksal/commands/refresh
@@ -2,29 +2,114 @@
 
 #: exec_target = cli
 
-## Initialize stack and site (full reset)
+## Refresh database, files, and import configuration
 ##
-## Usage: fin refresh [environment id]
+## Usage: fin refresh
 
-ENVIRONMENT=${1:-prod}
+# Abort if anything fails
+set -e
 
-cd /var/www/${DOCROOT}
+LIVE=false
+ELEMENTS='db'
 
-DBFILE="/tmp/site.${ENVIRONMENT}.sql"
-if [ ! -f $DBFILE ] || [ ! -z $(find $DBFILE -mmin +60) ] ; then
-
-    if [ ! -f $DBFILE ]; then
-        echo "Database file does not exist."
-    elif [ ! -z $(find $DBFILE -mmin +60) ]; then
-        echo "Database file is older then 1 hours"
-    fi
-
-    echo "Exporting ${ENVIRONMENT} Database..."
-    drush @remote.${ENVIRONMENT} sql-dump > $DBFILE
+# options may be followed by one colon to indicate they have a required argument
+if ! options=$(getopt -o s:e:d:l -l site:,env:,live,data: -- "$@")
+then
+    # something went wrong, getopt will put out an error message for us
+    exit 1
 fi
 
-echo "Truncating Database..."
-drush sql-drop -y
+while [ $# -gt 0 ]
+do
+    case $1 in
+    -s|--site) PANTHEON_SITE="$2"; shift ;;
+    -e|--env) PANTHEON_ENV="$2"; shift ;;
+    -l|--live) LIVE=true; ;;
+    -d|--data) ELEMENTS="$2"; shift;;
+    esac
+    shift
+done
 
-echo "Importing Database..."
-drush sql-cli < $DBFILE
+DOCROOT=${DOCROOT:-docroot};
+SITE_DIRECTORY=${SITE_DIRECTORY:-default};
+
+DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
+SITEDIR_PATH="${DOCROOT_PATH}/sites/${SITE_DIRECTORY}"
+
+cd $PROJECT_ROOT
+cd $SITEDIR_PATH
+
+if [ ! -d ~/tmp ]; then
+    mkdir ~/tmp
+fi
+
+if [ $ELEMENTS = 'all' ] || [ $ELEMENTS = 'db' ]; then
+    DBFILE="/tmp/${PANTHEON_ENV}.${PANTHEON_SITE}.sql"
+    if [ ! -f $DBFILE ] || [ ! -z $(find ${DBFILE} -mmin +360) ]; then
+     echo "${DBFILE} need updating"
+
+      echo "Exporting latest database..."
+      if [ -f $DBFILE ] && [ ! -z $(find ${DBFILE} -mmin +360) ]; then
+        rm -rf $DBFILE
+      fi
+
+      if $LIVE ; then
+        terminus env:wake ${PANTHEON_SITE}.${PANTHEON_ENV}
+        DBCONN=$(terminus connection:info ${PANTHEON_SITE}.${PANTHEON_ENV} --field="MySQL Command")
+        DBDUMP=${DBCONN/mysql /mysqldump }
+        eval $DBDUMP " --result-file=${DBFILE}"
+      else
+        COUNT=$(terminus backup:list ${PANTHEON_SITE}.${PANTHEON_ENV} --element=db --format=list | wc -l)
+        if [ $COUNT -eq 1 ]; then
+          echo "Creating backup on Pantheon..."
+          terminus backup:create ${PANTHEON_SITE}.${PANTHEON_ENV} --element=db
+        fi
+
+        LASTBKUP=$(terminus backup:list ${PANTHEON_SITE}.${PANTHEON_ENV} --element=db --field=date | head -n 1)
+        YESTERDAY=`date --date='yesterday' "+%Y-%m-%d %H:%M:%S"`
+
+        if [ "${LASTBKUP}" \< "${YESTERDAY}" ]; then
+          echo "Old backup on Pantheon...Creating new one..."
+          terminus backup:create ${PANTHEON_SITE}.${PANTHEON_ENV} --element=db
+        fi
+
+        terminus backup:get ${PANTHEON_SITE}.${PANTHEON_ENV} --element="db" --to="${DBFILE}.gz"
+        gunzip ${DBFILE}.gz
+      fi
+    fi
+
+    if [[ "$(${PROJECT_ROOT}/bin/drupal 2>/dev/null)" =~ "database:drop" ]]; then
+        echo "Dropping Old Database..."
+        ${PROJECT_ROOT}/bin/drupal database:drop -y
+    fi
+
+    echo "Importing Database..."
+    drush sql-cli < ${DBFILE}
+fi
+
+if [ $ELEMENTS = 'all' ] || [ $ELEMENTS = 'files' ]; then
+    cd $SITEDIR_PATH
+    echo "Downloading latest set of files from ${PANTHEON_SITE}..."
+
+    FILES_DIRECTORY=${PROJECT_ROOT}/sites/${SITE_DIRECTORY}/files
+    mkdir ${FILES_DIRECTORY}
+    if $LIVE ; then
+        if [ ! -d ${FILES_DIRECTORY} ]; then
+            mkdir ${FILES_DIRECTORY}
+        fi
+        cd $FILES_DIRECTORY
+      terminus rsync ${PANTHEON_SITE}.${PANTHEON_ENV}:files .
+    else
+      FILES="/tmp/${PANTHEON_ENV}.${PANTHEON_SITE}.tar.gz"
+      terminus backup:get ${PANTHEON_ENV}.${PANTHEON_SITE} --element=files --to="${FILES}"
+      rm -rf ${FILES_DIRECTORY}
+      tar -xf ${FILES}
+      mv files_* files
+    fi
+    echo "Fixing files directory permissions..."
+    chmod -R 755 files
+fi
+
+cd ${DOCROOT_PATH}
+#${PROJECT_ROOT}/.docksal/commands/site-build
+echo "Done!"
